# Generated by Django 4.1.3 on 2022-11-18 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('familia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familia',
            name='email',
        ),
    ]
